language: python

python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7-dev"

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

install:
  - pip install flake8
  - python setup.py develop

script:
  - flake8 ./mozsvc
  - python setup.py test
