language: python

python:
  - "2.7"

services:
  - memcached

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

install:
  - pip install flake8
  - CFLAGS="-Wno-error=write-strings" pip install .[memcache]

script:
  - flake8 ./mozsvc
  - python setup.py test
